### ISSUE TITLE
Change push API endpoint

### ISSUE THREAD

**Issue by jbanyer** [dineshpannu/efergy-to-chargehq#2]
Hi there,

The API endpoint has been changed, as per https://chargehq.net/kb/push-api

The new endpoint is:

`POST https://api.chargehq.net/api/public/push-solar-data`

The old endpoint is deprecated and will stop working at some point in the future.

Apologies for not mentioning this in my previous issue.

Cheers,
Jay.

**Comment by dineshpannu** [comment]
Ah, right. I missed that. Thanks for letting me know.
